server:
  port: 8080  # porta do gateway

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: produtor-service
          uri: http://localhost:8081   # URL/porta do seu MS Produtor
          predicates:
            - Path=/produtor/**
        - id: fazenda-service
          uri: http://localhost:8082   # URL/porta do seu MS Fazenda
          predicates:
            - Path=/fazenda/**
